<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>MoneyCounter.Infrastructure</AssemblyName>
    <RootNamespace>MoneyCounter.Infrastructure</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.0" />
    <PackageReference Include="SQLitePCLRaw.lib.e_sqlite3" Version="2.1.12" />
    <PackageReference Include="SQLitePCLRaw.bundle_e_sqlite3" Version="2.1.12" />
    <PackageReference Include="SQLitePCLRaw.core" Version="2.1.12" />
    <PackageReference Include="SQLitePCLRaw.provider.e_sqlite3" Version="2.1.12" />
    <ProjectReference Include="..\MoneyCounter.Core\MoneyCounter.Core.csproj" />
  </ItemGroup>
</Project>
